# config.jl — shared loader for the JSON reproduction configs.
#
# Every experiment driver in this directory reads its dataset, encoder and
# ordering settings from configs/*.json rather than hard-coding them. This exists
# because several published numbers were, at one point, only reproducible from a
# configuration that lived in a test file: the paper's CG cell for cnr-2000
# (2.329) could not be regenerated by any driver until the settings were
# recovered from test/run_tests_index_mode.jl.
module ReproConfig

using JSON
using Adjacently.IO: load_graph_from_pajek, load_adjacency_list_from_csv
using Adjacently.MGS: load_compressed_mgs3_graph, write_bg_mgs3_graph,
                      write_cs_mgs3_graph, write_cg_mgs3_graph
using Adjacently.Graph: get_core, subgraph
using Adjacently.Clustering: leiden_partition
using Adjacently.Relabeling: relabel_graph, relabel_graph_llp,
                             relabel_vertices_llp, merge_small_clusters
using Adjacently.Compression.CG: CGParams
using LightGraphs: nv, ne, vertices
using Random

export load_cfg, load_dataset, encode_bpe, apply_ordering, cg_k2_bpe, REPO_ROOT

const REPO_ROOT = normpath(joinpath(@__DIR__, "..", ".."))
const CFG_DIR   = joinpath(@__DIR__, "configs")

load_cfg(name) = JSON.parsefile(joinpath(CFG_DIR, name))

"Load a dataset by registry name, applying get_core where the registry says so."
function load_dataset(name::AbstractString)
    reg = load_cfg("datasets.json")["datasets"]
    haskey(reg, name) || error("unknown dataset '$name' (see configs/datasets.json)")
    d = reg[name]
    path = joinpath(REPO_ROOT, d["path"])
    isfile(path) || error("missing $path — for LAW graphs run fetch_datasets.sh first")
    g = d["loader"] == "pajek" ? load_graph_from_pajek(path) :
        d["loader"] == "csv"   ? load_adjacency_list_from_csv(path, ',', true) :
                                 load_compressed_mgs3_graph(path)
    d["core"] === true && (g = get_core(g)[1])
    return g
end

"Merge per-encoder defaults with the per-dataset overrides from encoders.json."
function encoder_params(enc::AbstractString, dataset::AbstractString)
    e = load_cfg("encoders.json")[enc]
    p = copy(e["_defaults"])
    haskey(e["per_dataset"], dataset) && merge!(p, e["per_dataset"][dataset])
    return p
end

sym(x) = x isa AbstractString ? Symbol(x) : x

"Encode `g` with encoder `enc` under the registry config; return bpe."
function encode_bpe(g, enc::AbstractString, dataset::AbstractString, base::AbstractString)
    p = encoder_params(enc, dataset); m = ne(g)
    if enc == "bg"
        write_bg_mgs3_graph(g, base; integer_encoding=sym(p["integer_encoding"]),
            ref_window_size=p["ref_window_size"], copy_blocks=p["copy_blocks"],
            stop_deltas=p["stop_deltas"], lr_split=p["lr_split"],
            multi_ref=p["multi_ref"], cost_model=p["cost_model"])
    elseif enc == "cs"
        write_cs_mgs3_graph(g, base; integer_encoding=sym(p["integer_encoding"]),
            ref_window_size=p["ref_window_size"], lr_split=p["lr_split"],
            cost_model=p["cost_model"])
    else
        error("encoder '$enc' has no generic path; CG uses cg_k2_bpe")
    end
    return 8 * filesize(base * ".mgz") / m
end

"CG at the recovered paper configuration (K=2: largest Leiden community vs rest)."
function cg_k2_bpe(g, base::AbstractString; window::Union{Nothing,Int}=nothing)
    c = load_cfg("encoders.json")["cg_k2_paper"]
    raw = copy(c["params"]); window !== nothing && (raw["intra_ref_window"] = window)
    kw = Dict{Symbol,Any}()
    for (k, v) in raw
        kw[Symbol(k)] = v isa AbstractString ? Symbol(v) : v
    end
    params = CGParams(; kw...)
    T = eltype(g); n = Int(nv(g))
    Random.seed!(0)
    part = leiden_partition(g; max_passes=c["leiden"]["max_passes"],
                               max_levels=c["leiden"]["max_levels"])
    counts = Dict{Int,Int}(); for x in part; counts[x] = get(counts, x, 0) + 1; end
    top = sort(collect(keys(counts)); by=l->counts[l], rev=true)[1]
    clusters = [T[], T[]]
    for i in 1:n; push!(clusters[part[i] == top ? 1 : 2], T(i)); end
    for C in clusters; sort!(C); end
    write_cg_mgs3_graph(g, base, clusters; coding_scheme=sym(c["coding_scheme"]),
        integer_encoding=sym(c["integer_encoding"]), params=params)
    return 8 * filesize(base * ".mgz") / ne(g)
end

"Apply a named ordering from orderings.json."
function apply_ordering(g, ordering::AbstractString, dataset::AbstractString; seed::Int=0)
    o = load_cfg("orderings.json")["orderings"]
    haskey(o, ordering) || error("unknown ordering '$ordering'")
    spec = o[ordering]; Random.seed!(seed)
    spec["kind"] == "identity" && return g
    if spec["kind"] == "llp"
        return relabel_graph_llp(g; llp_mode=sym(spec["llp_mode"]), passes=spec["passes"])[1]
    end
    τ = nothing
    if haskey(spec, "merge_clusters_per_dataset")
        τ = get(spec["merge_clusters_per_dataset"], dataset, nothing)
    elseif haskey(spec, "merge_clusters")
        τ = spec["merge_clusters"]
    end
    T = eltype(g); part = leiden_partition(g)
    (τ !== nothing && τ isa Integer && τ > 1) && (part = merge_small_clusters(g, part, τ))
    groups = Dict{Int,Vector{T}}()
    for v in vertices(g); push!(get!(groups, part[Int(v)], T[]), T(v)); end
    ks = collect(keys(groups))
    spec["sort_clusters"] == "size_desc" ? sort!(ks, by=k->(-length(groups[k]), k)) :
                                           sort!(ks, by=k->( length(groups[k]), k))
    order = T[]
    for k in ks
        C = sort(groups[k])
        if length(C) > 2
            sg, oni, _ = subgraph(g, C)
            mp = relabel_vertices_llp(sg, sym(spec["llp_mode"]); passes=spec["llp_passes"])
            sort!(C, by=v->Int(mp[oni[v]]))
        end
        append!(order, C)
    end
    vm = Dict{T,T}(); for (i, o2) in enumerate(order); vm[o2] = T(i); end
    return relabel_graph(g, vm)
end

end # module
